language: go

sudo: required

dist: trusty

go_import_path: istio.io/auth

go:
- 1.7.x

jdk:
- oraclejdk8

env:
  global:
  - BAZEL_VERSION=0.4.4

addons:
  apt:
    packages:
    - wget

cache:
  directories:
  - $HOME/bazel/install

before_install:
- mkdir -p ${HOME}/bazel/install
- cd ${HOME}/bazel/install
- wget --no-clobber "https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/bazel_${BAZEL_VERSION}-linux-x86_64.deb"
- chmod +x bazel_${BAZEL_VERSION}-linux-x86_64.deb
- sudo dpkg -i bazel_${BAZEL_VERSION}-linux-x86_64.deb
- sudo apt-get -f install -qqy
- cd ${TRAVIS_BUILD_DIR}

install:
# Install GoMetaLinter and known linters.
- go get github.com/alecthomas/gometalinter
- gometalinter --install --vendored-linters

script:
- bazel test //...
- bin/setup.sh # This must be run before linters and coverages.
- bin/linters.sh
- bin/coverage.sh
- bin/headers.sh

after_success:
- bash <(curl -s https://codecov.io/bash)
