language: go

sudo: required

dist: trusty

go:
- 1.7.x

jdk:
- oraclejdk8

env:
  global:
  - BAZEL_VERSION=0.4.4

addons:
  apt:
    packages:
    - wget

cache:
  directories:
  - $HOME/bazel/install
  - $HOME/bazel/outbase

before_install:
- mkdir -p ${HOME}/bazel/install
- cd ${HOME}/bazel/install
- wget --no-clobber "https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/bazel_${BAZEL_VERSION}-linux-x86_64.deb"
- chmod +x bazel_${BAZEL_VERSION}-linux-x86_64.deb
- sudo dpkg -i bazel_${BAZEL_VERSION}-linux-x86_64.deb
- sudo apt-get -f install -qqy
- cd ${TRAVIS_BUILD_DIR}

install: true # disable the default install step

script:
- bazel --output_base=$HOME/bazel/outbase test //...
- bin/check_format.sh
